### ISSUE TITLE
NPE retrieving a Block

### ISSUE THREAD

**Issue by fdiotalevi** [blockchain/api-v1-client-java#15]
While using the LATEST version, if I retrieve the block 0000000000000000011cb67e10662cdca9f8a5c8ea0f23d1e6fc5027539d684a

    BlockExplorer blockExplorer = new BlockExplorer();
    Block block = blockExplorer.getBlock("0000000000000000011cb67e10662cdca9f8a5c8ea0f23d1e6fc5027539d684a");

I obtain

Exception in thread "main" java.lang.NullPointerException
	at info.blockchain.api.blockexplorer.Output.<init>(Output.java:36)
	at info.blockchain.api.blockexplorer.Output.<init>(Output.java:31)
	at info.blockchain.api.blockexplorer.Transaction.<init>(Transaction.java:71)
	at info.blockchain.api.blockexplorer.Block.<init>(Block.java:70)
	at info.blockchain.api.blockexplorer.BlockExplorer.getBlock(BlockExplorer.java:89)
	at com.knokode.bitcoin.explorer.Main.main(Main.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

**Comment by mik3hall** [comment]
> On Oct 21, 2015, at 4:20 PM, Filippo Diotalevi <notifications@github.com> wrote:
> 
> at info.blockchain.api.blockexplorer.Output.(Output.java:36)

With, I think the latest, line 36 in Output.java for me is only the character }
Fwiw, I haven’t run into this issue, while doing a fair amount of testing, since installing the version that was supposed to have the fix.

Michael Hall

**Comment by matsjj** [comment]
Although I haven't ran into this issue as well, I changed a minor thing that could have ended up in a NPE in the Output class. 

Can you confirm that you actually run the latest git version? The maven repository is no longer supported, I removed it from the README as well.

**Comment by fdiotalevi** [comment]
Thanks,
I was actually using the maven repo, I'll try to clone the github repo and
build from sources tonight

Filippo
