### ISSUE TITLE
Bad responce format in ExchangeRates().toFiat

### ISSUE THREAD

**Issue by POSTAL5532** [blockchain/api-v1-client-java#47]
Hey. Today I sat down to study your api. So there was a small problem in the example line:
`BigDecimal BTCToUSD = exchange.toFiat("USD", new BigDecimal(100000000));` - throw 

java.lang.NumberFormatException
at java.math.BigDecimal.<init>(BigDecimal.java:494)
	at java.math.BigDecimal.<init>(BigDecimal.java:383)
	at java.math.BigDecimal.<init>(BigDecimal.java:806)
	at info.blockchain.api.exchangerates.ExchangeRates.toFiat(ExchangeRates.java:96)

I ran the code in debug mode and found that in the line 
`return new BigDecimal(response);` 
in ExchangeRates().toFiat() in response, the value is returned in the following form: 819,060,000,000. I'm not a very experienced developer, but it seems to me that BigDecimal can not process commas in this sense. I will be glad to any answer. Thank you and sorry for my english)

**Comment by POSTAL5532** [comment]
`public class CustomExchangeRates extends ExchangeRates {
    @Override
    public BigDecimal toFiat(String currency, BigDecimal value) throws APIException, IOException {
        Map<String, String> params = new HashMap();
        params.put("currency", currency);
        params.put("value", String.valueOf(value.multiply(BigDecimal.valueOf(100000000L))));

        String response = HttpClient.getInstance().get("frombtc", params);
        response = response.replaceAll(",", "");
        System.out.println(response);
        return new BigDecimal(response);
    }
}`

It's work for me!
